Bump v4l2loopback version to fix build error with 6.16.
Fixes build error due to missing macro HAVE_TIMER_SETUP.

```
20:07:04 [qb.build_rpm.linux-kernel-latest.host-fc37.build] DEBUG:   CC [M]  v4l2loopback.o
20:07:04 [qb.build_rpm.linux-kernel-latest.host-fc37.build] DEBUG: v4l2loopback.c: In function 'v4l2_loopback_add':
20:07:04 [qb.build_rpm.linux-kernel-latest.host-fc37.build] DEBUG: v4l2loopback.c:2904:9: error: implicit declaration of function 'setup_timer' [-Werror=implicit-function-declaration]
20:07:04 [qb.build_rpm.linux-kernel-latest.host-fc37.build] DEBUG:  2904 |         setup_timer(&dev->sustain_timer, sustain_timer_clb, nr);
20:07:04 [qb.build_rpm.linux-kernel-latest.host-fc37.build] DEBUG:       |         ^~~~~~~~~~~
20:07:04 [qb.build_rpm.linux-kernel-latest.host-fc37.build] DEBUG: cc1: some warnings being treated as errors
20:07:04 [qb.build_rpm.linux-kernel-latest.host-fc37.build] DEBUG: make[3]: *** [/builddir/build/BUILD/kernel-latest-6.16.1/linux-6.16.1/scripts/Makefile.build:287: v4l2loopback.o] Error 1
```